### ISSUE TITLE
Unhandled errors when invalid credentials are uploaded

### ISSUE THREAD

**Issue by lieszkol** [zaxbux/oc-gmaildriver-plugin#1] opened 2019-06-11 11:34 UTC
Thanks for this plugin! Unfortunately I ran into three issues.

Issue 1
-------
When going through your steps, at first I skipped step 6 and 7

> 6. Copy the Authorized Redirect URI from the backend Gmail configuration page.
> 7. Add that URI as an Authorized redirect URI and click Create
Since I figured I can configure restrictions later.

After completing step 10
> 10. Upload the file you downloaded to the backend Gmail configuration page and save the settings. Reload the page to show the Authorize button.
I got the following bug, and could no longer access the plugin configuration screen:
`"Undefined index: expires_in" on line 470 of /var/www/lineahotels.hu/public_html/plugins/zaxbux/gmailmailerdriver/vendor/google/apiclient/src/Google/Client.php`

Note that it is also possible to get here if the user forgets to hit "enter" after entering the redirect URI on google's pages, which is an easy mistake to make, because google doesn't warn the user that the URI wasn't actually added/saved.

Issue 2
-------
So I figured I'll delete the uploaded JSON credential file, which I did (somewhere under /storage/app/uploads/protected/...) as well as the corresponding file from the system_files table.

At this point I was able to again access the plugin config page. I completed steps 6 and 7 above which I skipped previously, and re-uploaded the JSON file.

Now, I got this error:
`"Undefined index: expires_in" on line 470 of /var/www/lineahotels.hu/public_html/plugins/zaxbux/gmailmailerdriver/vendor/google/apiclient/src/Google/Client.php`

Issue 3
-------
So I figured OK, I'll delete the plugin and re-add it. So I did so and went through all of the steps and got to step 11:
> 11. Click the Authorize button to open the Google consent page. Continue to select the account you want to send email with and consent to sending email on your behalf.

After authorizing the plugin through the google dialogs, when it returned to OctoberCMS I got this error:

    Object of class Illuminate\Support\Facades\Response could not be converted to string
    /var/www/lineahotels.hu/public_html/vendor/october/rain/src/Html/BlockBuilder.php line 80

I'm attaching the full error page: 
[Exception.zip](https://github.com/zaxbux/oc-gmaildriver-plugin/files/3276256/Exception.zip)

So now I'm stuck. 

Any ideas?

**Comment by zaxbux** [comment] 2019-06-11 20:56
Thanks for the bug report. I've done some investigating, although I couldn't exactly reproduce your steps to get all of the errors you encountered.

### Issue 1
- The authorized redirect URI is required for the Google API to work.
- The error you had after step 10 is related to the temporary authorization token that is generated after completing the authorization. This likely failed because there was no redirect URI for the plugin to generate the temporary token from.

### Issue 2
- There is also a hidden temporary authorization token that is present in the database, but since it wasn't fully generated from step 10, the Google API client encountered an unhandled exception.

### Issue 3
- Deleting the plugin doesn't seem to clear the temporary token from the settings. In order to remove the credential file and temporary token, the "Reset to default" button has to be clicked.
- The exception about `BlockBuilder.php` was an error in my code, the wrong response type was being returned.

---

I've made some code changes, and I'm testing them currently. Once I have updated the plugin in the October CMS marketplace, I'll close this issue. Thanks for all the information!

**Comment by zaxbux** [comment] 2019-06-12 02:27
Plugin has been tested and no longer behaves unexpectedly when the uploaded credentials are not complete. The plugin will also provide some useful (hopefully) feedback. It is currently updating on the October CMS marketplace.

**Closed as completed by zaxbux** 2019-06-12 02:27 UTC
Labels: Type: Bug, Status: Complete

**Comment by lieszkol** [comment] 2019-06-12 09:24
Thank you Zachary! And thanks for this free plugin!
